### ISSUE TITLE
Update meta-data fetching for digital objects.

### ISSUE THREAD

**Issue by ZogopZ** [ICOS-Carbon-Portal/pylib#80]
- [x] Change metadata for dobj. (Merge info1, info2, info3 e.t.c.)
- [x]  Grab the meta-data using .json instead. (rewrite pylib’s calls carefully not to break any notebooks). 
- [x] Create future warning for `.info` and implement `.get` for json or implement it in info. 

Content grabbed from https://fileshare.icos-cp.eu/apps/onlyoffice/2309542?filePath=%2FCP%20groupdisk%2FElaborated%20Products%2FPlanning%2Fpylib%20list.docx
